name: BCC Build only

on: push

jobs:
  test_bcc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [{version: "18.04", nick: bionic}, {version: "20.04", nick: focal}]
        env:
        - TYPE: Release
          PYTHON_TEST_LOGFILE: critical.log
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: System info
      run: |
        uname -a
        ip addr
    - name: Build docker container with all deps
      run: |
        docker build \
        --build-arg UBUNTU_VERSION=${{ matrix.os.version }} \
        --build-arg UBUNTU_SHORTNAME=${{ matrix.os.nick }} \
        -t bcc-docker -f docker/Dockerfile.tests .
    - name: Run bcc build
      env: ${{ matrix.env }}
      run: |
        /bin/bash -c \
                   "docker run --privileged \
                   --pid=host \
                   -v $(pwd):/bcc \
                   -v /sys/kernel/debug:/sys/kernel/debug:rw \
                   -v /lib/modules:/lib/modules:ro \
                   -v /usr/src:/usr/src:ro \
                   -v /usr/include/linux:/usr/include/linux:ro \
                   bcc-docker \
                   /bin/bash -c \
                   'mkdir -p /bcc/build && cd /bcc/build && \
                    cmake -DCMAKE_BUILD_TYPE=${TYPE} \
                          -DCMAKE_C_COMPILER=/usr/bin/gcc-10 \
                          -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 \
                          -DLLVM_DIR=/clang+llvm10/lib/cmake/llvm .. && \
                          make -j9'"
